### PR TITLE
extend date/time datatype limits to cover age of universe

### LINKED ISSUE #309: Age of universe is out of range
```
<http://www.wikidata.org/entity/Q500699> <http://www.wikidata.org/prop/direct/P571> "-13798000000-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> . 
``` 
is a triple from wikidata that describes the [age of the universe](https://www.wikidata.org/wiki/Q500699). 
Parsing it with rdf4cpp causes 
```
11656420:159(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -13798000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
```

There is also a bunch of others ranging up to 100000000000000:
```
867553:157(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -3500000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
11656420:159(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -13798000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
14191233:158(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -2800000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
14191234:158(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -2500000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
17781438:158(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -2300000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
170463886:161(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -13600000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
587159344:161(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -13800000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
977704275:161(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -4107615843 is out of range. note: position may not be accurate and instead point to the end of the triple.
1064375892:155(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -4527000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1066824060:158(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -13200000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1067510329:158(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -4600000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1068075066:158(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -2500000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1073936144:158(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -3700000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1073936145:158(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -3000000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1079918287:158(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -4000000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1079918288:158(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -3600000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1080898198:159(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -12500000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1084516237:159(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -3850000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1084516238:159(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -3800000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1099493579:160(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -13798000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1099493580:163(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: 100000000000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1120696842:160(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: 297876676000 is out of range. note: position may not be accurate and instead point to the end of the triple.
1129023449:159(bad literal): http://www.w3.org/2001/XMLSchema#dateTime parsing error: -2400000000 is out of range. note: position may not be accurate and instead point to the end of the triple.
```

Rdf4cpp should support all these triples. Also the error message should clearly state that it is the year which is out of range. But the real challange lies in the [future of the universe](https://en.wikipedia.org/wiki/Future_of_an_expanding_universe). Not that it is relevant for any appointment we'll ever have but we should be able to store and process information about cosmic time spans.

### PR DESCRIPTION
**Pull request by mcb5637**

### CODE REVIEW

File: src/rdf4cpp/Timezone.hpp [hunk 1]
```diff
@@ -130,23 +132,144 @@ struct Timezone {
 
 using OptionalTimezone = std::optional<Timezone>;
 
-using TimePoint = std::chrono::time_point<std::chrono::local_t, std::chrono::milliseconds>;
+template<typename I = int64_t>
+struct Year {
```
Comment (liss-h) [inline src/rdf4cpp/Timezone.hpp:135]: I think it would probably make sense to clone as much of the interface of `std::chrono::year` as possible, as this type is part of the API surface

File: src/rdf4cpp/Timezone.hpp [hunk 2]
```diff
@@ -130,23 +132,144 @@ struct Timezone {
...
+
+    [[nodiscard]] constexpr bool is_leap() const noexcept(noexcept(year % 100)) {
+        return year % 4 == 0 && (year % 100 != 0 || year % 400 == 0);
+    }
+
+    constexpr auto operator<=>(Year const &) const noexcept = default;
+};
+
+template<typename Y = int64_t>
+struct Date {
```
Comment (liss-h) [inline src/rdf4cpp/Timezone.hpp]: This corresponds to `chrono::year_month_day` right? If so I think it makes sense to name it `YearMonthDay` for consistency

File: src/rdf4cpp/Timezone.hpp [hunk 3]
```diff
@@ -175,6 +298,80 @@ struct dice::hash::dice_hash_overload<Policy, rdf4cpp::OptionalTimezone> {
...
+struct std::formatter<rdf4cpp::ZonedTime > : std::formatter<string_view> {
+    auto format(rdf4cpp::ZonedTime const &p, format_context &ctx) const {
+        return std::format_to(ctx.out(), "{}{}", p.get_local_time(), p.get_time_zone().to_canonical_string());
+    }
+};
+
+namespace rdf4cpp {
+    template<typename Y>
+    std::ostream &operator<<(std::ostream &os, rdf4cpp::Year<Y> const &value) {
+        os << std::format("{}", value);
```
Comment (liss-h) [inline src/rdf4cpp/Timezone.hpp]: `format_to` with ostream iterator (also below)

File: src/rdf4cpp/datatypes/registry/util/CharConvExt.hpp [hunk 4]
```diff
@@ -11,6 +11,8 @@
 
 #include <rdf4cpp/InvalidNode.hpp>
 
+#include <boost/multiprecision/cpp_int.hpp>
```
Comment (liss-h) [inline src/rdf4cpp/datatypes/registry/util/CharConvExt.hpp]: is this left over or actually used?

File: src/rdf4cpp/Timezone.hpp [hunk 5]
```diff
@@ -130,23 +132,144 @@ struct Timezone {
 
 using OptionalTimezone = std::optional<Timezone>;
 
-using TimePoint = std::chrono::time_point<std::chrono::local_t, std::chrono::milliseconds>;
+template<typename I = int64_t>
```
Comment (liss-h) [inline src/rdf4cpp/Timezone.hpp]: Since we are only using `int64_t` it would make sense to remove the template

File: src/rdf4cpp/datatypes/registry/util/DateTimeUtils.hpp [hunk 6]
```diff
@@ -154,70 +169,76 @@ inline char *canonical_seconds_remove_empty_millis(char *it) {
...
+    auto apply_timezone = [](const rdf4cpp::TimePoint& t, rdf4cpp::Timezone tz) noexcept -> std::optional<rdf4cpp::TimePointSys> {
+        try {
+            return rdf4cpp::ZonedTime{tz, t}.get_sys_time();
+        } catch (const std::overflow_error&) {
+            return std::nullopt;
+        }
+    };
+
+    auto const cmp = [](const auto& a, const auto& b) noexcept -> std::partial_ordering {
+        if (a == b)
```
Comment (liss-h) [inline src/rdf4cpp/datatypes/registry/util/DateTimeUtils.hpp:207]: leftover from `cpp_int` support?

File: src/rdf4cpp/util/CheckedInt.hpp [hunk 7]
```diff
@@ -7,7 +7,8 @@ namespace rdf4cpp::util {
  * Designed to be used in std::chrono::duration, but may be used standalone.
  * @tparam I Integer type to wrap
  */
-template<std::integral I>
+template<typename I>
+requires (std::integral<I> || std::same_as<I, __int128> || std::same_as<I, unsigned __int128>)
```
Comment (liss-h) [inline src/rdf4cpp/util/CheckedInt.hpp]: leftover from experimenting?

**Review by liss-h — CHANGES_REQUESTED** [review]
Hi, thx for the PR.
This is the first review, I did not look at the logic yet but I found some things that (at least I'm assuming) are left over from trying things out in the beginning

File: src/rdf4cpp/datatypes/registry/util/DateTimeUtils.hpp (hunk 6 above)
Comment (mcb5637) [reply src/rdf4cpp/datatypes/registry/util/DateTimeUtils.hpp:207]: Its still needed, because TimePoint uses a cpp_int.

File: src/rdf4cpp/Timezone.hpp (hunk 5 above)
Comment (mcb5637) [reply src/rdf4cpp/Timezone.hpp]: test cases use `int`. also keeping the template makes it easier to adjust in the future.

File: src/rdf4cpp/Timezone.hpp (hunk 2 above)
Comment (mcb5637) [reply src/rdf4cpp/Timezone.hpp]: The xsd datatype is `http://www.w3.org/2001/XMLSchema#date`, thats why i named it Date.

File: src/rdf4cpp/Timezone.hpp (hunk 5 above)
Comment (liss-h) [reply src/rdf4cpp/Timezone.hpp]: Since we will not be using `int` in the real world I would suggest to change the tests to `uint64_t`. Regarding the template: I don't think we'll need to change it in the future

File: src/rdf4cpp/Timezone.hpp (hunk 2 above)
Comment (liss-h) [reply src/rdf4cpp/Timezone.hpp]: for consistency with std and the `YearMonth` type I would still prefer `YearMonthDay`

**Review by liss-h — CHANGES_REQUESTED** [review]
one change request open

**Review by liss-h — APPROVED** [review]
