### PR TITLE
unicode fixes

### LINKED ISSUE #161: Bug: Unicode support for more string functions
SPARQL functions that expect unicode support, but currently only support ASCII

- [x] literal ctor should normalize strings to NFC
- [x] then modify any comparisons to not do a normalization themselves

- [x] SUBSTR
- [x] STRSTARTS
- [x] STRENDS
- [x] CONTAINS
- [x] STRBEFORE
- [x] STRAFTER
- [x] make_lang_tagged (convert lang tag to lowercase)
- [x] make_typed_from_value (does currently not convert lang tag to lowercase, add)
- [x] operator == (will be fixed by ctor normalization)

to implememt, use https://github.com/uni-algo/uni-algo
also these functions need to be adapted to the new libraray:

- [x] STRLEN 
- [x] ENCODE_FOR_URI

after that, the old utf8 lib can be removed

### PR DESCRIPTION
**Pull request by mcb5637**
resolve #161

### CODE REVIEW

**Comment by bigerl** [comment]
We could also store string unicode NFC in the first place. Please check the RDF specs if anything speaks against it. Would help with deduplication.

It would also make sense to normalize IRIs. It would involve unicode as well, I guess. But that would be a separate issue.

File: src/rdf4cpp/rdf/Literal.cpp [hunk 1]
```diff
@@ -54,9 +56,10 @@ Literal Literal::make_noninlined_special_unchecked(std::any &&value, storage::no
 }
 
 Literal Literal::make_lang_tagged_unchecked(std::string_view lexical_form, std::string_view lang, Node::NodeStorage &node_storage) noexcept {
+    auto lf = una::norm::to_nfc_utf8(lexical_form);
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: You are normalizing twice in some cases, e.g. when calling `make_lang_tagged`. Don't normalize here, this function is not meant to do anything to the input data except putting it into storage.

File: src/rdf4cpp/rdf/Literal.cpp [hunk 2]
```diff
@@ -29,9 +30,10 @@ Literal Literal::make_null() noexcept {
 }
 
 Literal Literal::make_simple_unchecked(std::string_view lexical_form, Node::NodeStorage &node_storage) noexcept {
+    auto lf = una::norm::to_nfc_utf8(lexical_form);
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: Same here, do not normalize in `*_unchecked` functions.

File: src/rdf4cpp/rdf/Literal.cpp [hunk 3]
```diff
@@ -1319,13 +1317,25 @@ Literal Literal::regex_replace(Literal const &pattern, Literal const &replacemen
     return this->regex_replace(*repl, node_storage);
 }
 
-util::TriBool Literal::contains(std::string_view const needle) const noexcept {
+util::TriBool Literal::contains_normalized(std::string_view const needle) const noexcept {
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: This is still an open question, just highlighting this for later
- [ ] figure out if we actually want to normalize the inputs

**Review by liss-h — CHANGES_REQUESTED** [review]
We are still kind of waiting for a resolution for the normalization discussion, but I'll leave some small comments for now

And while I'm at it I'll just leave a list of the options we discussed here

Equality interpretations:
1. equality (and other related stuff) happens after both operands are normalized
2. equality (and other related stuff) happens without modifying the operands in any way

Related: do we want to normalize before putting strings to storage?
1. Yes
2. No, only check if the unicode is valid, normalized or not (=> also do not normalize on equality operator and similar)

Arguments for 1: (in no particular order)
- this is the way the unicode people intended it (which begs the question why there are multiple ways to represent the same character at all)
- theoretically some dedup (minor at best)
- unnormalized and normalized chars represent the same thing in the real world
- rdf recommends it
- consistency with the way we implement numeric normalization

Arguments for 2: (in no particular order)
- normalization changes user data (precedence that this doesn't matter is set by numeric types)
- performance
- code reduction (minor)
- precendence in other programming languages (and I would say SPARQL is kind of something simmilar)
- rdf _only_ recommends it which means we can just not do it

The wikidata query service is inconsistent (whichever triplestore that is) some queries normalize the strings others don't, weird.

Hopefully I got everything and didn't misrepresent anything

File: src/rdf4cpp/rdf/Literal.cpp [hunk 4]
```diff
@@ -106,20 +106,32 @@ bool Literal::dynamic_datatype_eq_impl(std::string_view datatype) const noexcept
     return this->datatype().identifier() == datatype;
 }
 
-Literal Literal::make_simple(std::string_view lexical_form, Node::NodeStorage &node_storage) {
-    return Literal::make_simple_unchecked(lexical_form, node_storage);
+Literal Literal::make_simple(std::string_view lexical_form, Node::NodeStorage &node_storage, bool normalize) {
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: Please don't use a boolean flag, I know alex and nikos like to do that way too much 😉 but its not very pleasant to read at the call site, because looking at the code you just read:
```c++
auto l = Literal::make_simple("spherical cow", some_node_storage, true);
```
and then you have to go to the declaration and check what that `true` even means. (IDE highlighting can help but thats really unreliable).

Would prefer if this would read:
```c++
auto l = Literal::make_simple("ferris", some_node_storage, FindGoodNameForEnum::Normalize); //option a
auto l_alt = Literal::make_simple_normalize("moo", some_node_storage); // option b
```

Maybe it also makes sense to reverse the parameters but I'm not sure which use case (custom node storage, normalization) is more likely, so I don't really have a strong opinion on that.

File: src/rdf4cpp/rdf/Literal.cpp [hunk 5]
```diff
@@ -106,20 +106,32 @@ bool Literal::dynamic_datatype_eq_impl(std::string_view datatype) const noexcept
...
+    if (normalize) {
+        const auto ln = una::norm::to_nfc_utf8(lexical_form);
+        return Literal::make_simple_unchecked(ln, node_storage);
+    } else {
+        if (una::norm::is_nfc_utf8(lexical_form))
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: This is only supposed to check for _any_ valid utf8. It should not only accept nfc.

File: src/rdf4cpp/rdf/Literal.cpp [hunk 6]
```diff
@@ -106,20 +106,32 @@ bool Literal::dynamic_datatype_eq_impl(std::string_view datatype) const noexcept
...
+            return Literal::make_simple_unchecked(lexical_form, node_storage);
+        else
+            return Literal{};
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: throw exception instead to make it consistent with behaviour of other malformed datatype inputs. (e.g. `xsd:integer`)

File: src/rdf4cpp/rdf/Literal.cpp [hunk 7]
```diff
@@ -106,20 +106,32 @@ bool Literal::dynamic_datatype_eq_impl(std::string_view datatype) const noexcept
...
 }
 
-Literal Literal::make_lang_tagged(std::string_view lexical_form, std::string_view lang_tag, Node::NodeStorage &node_storage) {
-    std::string lowercase_lang_tag;
-    std::transform(lang_tag.begin(), lang_tag.end(), std::back_inserter(lowercase_lang_tag), [](char const ch) {
-        return static_cast<char>(std::tolower(ch));
-    });
-
-    return Literal::make_lang_tagged_unchecked(lexical_form, lowercase_lang_tag, node_storage);
+Literal Literal::make_lang_tagged(std::string_view lexical_form, std::string_view lang_tag, Node::NodeStorage &node_storage, bool normalize) {
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: same thing with the boolean as above

File: src/rdf4cpp/rdf/Literal.cpp [hunk 8]
```diff
@@ -385,17 +397,19 @@ Literal::operator std::string() const noexcept {
                     break;
                 }
                 [[likely]] default : {
-                    out << character;
-                    break;
-                }
+                        out << character;
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: formatting got messed up

File: src/rdf4cpp/rdf/Literal.cpp [hunk 9]
```diff
@@ -385,17 +397,19 @@ Literal::operator std::string() const noexcept {
...
+                    }
             }
         }
         out << "\"";
     };
 
     std::ostringstream oss;
 
-    if (this->is_inlined()) {
+    if (this->null()) {
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp:414]: good idea

File: src/rdf4cpp/rdf/Literal.cpp [hunk 10]
```diff
@@ -1570,11 +1600,12 @@ Literal Literal::substr(size_t start, size_t len, Node::NodeStorage &node_storag
 
     auto const s = this->lexical_form();
 
-    if (start > s.size()) {
+    if (start > this->strlen()) {
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: I don't think this check makes sense anymore with unicode support, as it requires iteration of the whole string. (hope the `una` views just return an empty view if the start index is too large)

File: src/rdf4cpp/rdf/Literal.cpp [hunk 11]
```diff
@@ -1658,6 +1689,10 @@ Literal Literal::sha512(NodeStorage &node_storage) const {
     return this->hash_with("SHA2-512", node_storage);
 }
 
+std::string Literal::normalize_unicode(std::string_view utf8) {
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: I would say this should be a free function, as it doesn't really have anything to do with `Literal`

File: src/rdf4cpp/rdf/Literal.hpp [hunk 12]
```diff
@@ -231,20 +238,22 @@ class Literal : public Node {
...
      * @param compatible_value instance for which the literal is created
      * @param node_storage NodeStorage used
+     * @param normalize normalize lexical_form to UTF-8 NFC instead of failing (only for xsd::string/rdf::langString)
      * @return literal instance representing compatible_value
      */
     template<datatypes::LiteralDatatype T>
     [[nodiscard]] static Literal make_typed_from_value(typename T::cpp_type const &compatible_value,
-                                                       NodeStorage &node_storage = NodeStorage::default_instance()) noexcept {
+                                                       NodeStorage &node_storage = NodeStorage::default_instance(),
+                                                       bool normalize = false) noexcept {
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.hpp]: same thing with the bool here

File: src/rdf4cpp/rdf/Literal.cpp [hunk 13]
```diff
@@ -1388,13 +1408,13 @@ Literal Literal::substr_after(std::string_view const needle, Node::NodeStorage &
...
 
-    if (pos == std::string_view::npos) {
+    const auto r = una::casesens::search_utf8(s.view(), needle);
+
+    if (!r)
         return Literal::make_simple_unchecked("", node_storage);
-    }
 
-    auto const substr = s.view().substr(pos + needle.size());
+    auto substr = static_cast<std::string_view>(s.view()).substr(r.pos() + needle.size());  // search_utf8 returns byte position, not unicode character position
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: why the `static_cast` to `std::string_view`?

File: src/rdf4cpp/rdf/Literal.cpp [hunk 14]
```diff
@@ -1570,11 +1600,12 @@ Literal Literal::substr(size_t start, size_t len, Node::NodeStorage &node_storag
 
     auto const s = this->lexical_form();
 
-    if (start > s.size()) {
+    if (start > this->strlen()) {
         return Literal::make_string_like_copy_lang_tag("", *this, node_storage);
     }
 
-    auto const substr = s.view().substr(start, len);
+    auto substr = s.view() | una::ranges::views::utf8 | una::views::drop(start) | una::views::take(len) | una::ranges::to_utf8<std::string>();
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp:1608]: Can this somehow be converted to a `string_view` without an allocation? In theory it should work, not sure if the interface of `una` allows that tho.

**Review by liss-h — CHANGES_REQUESTED** [review]
Mostly interface stuff, some minor implementation things.

File: src/rdf4cpp/rdf/Literal.cpp (hunk 13 above)
Comment (mcb5637) [reply src/rdf4cpp/rdf/Literal.cpp]: to use `std::string_view::substr` instead of `std::string::substr`, which does not allocate any memory

Comment (liss-h) [reply src/rdf4cpp/rdf/Literal.cpp]: `s.view()` returns a `std::string`?

File: src/rdf4cpp/rdf/Literal.cpp (hunk 10 above)
Comment (mcb5637) [reply src/rdf4cpp/rdf/Literal.cpp]: removed it, and added a test case just in case it does not

File: src/rdf4cpp/rdf/Literal.cpp (hunk 13 above)
Comment (mcb5637) [reply src/rdf4cpp/rdf/Literal.cpp]: oh, you are correct
that s.view() was a std::string in one of the previous versions and i forgot to remove the cast

File: src/rdf4cpp/rdf/Literal.cpp (hunk 14 above)
Comment (mcb5637) [reply src/rdf4cpp/rdf/Literal.cpp:1608]: no

Comment (liss-h) [reply src/rdf4cpp/rdf/Literal.cpp:1608]: Sad. Its fine then

File: src/rdf4cpp/rdf/Literal.hpp [hunk 15]
```diff
@@ -165,33 +165,53 @@ class Literal : public Node {
...
      */
     [[nodiscard]] static Literal make_simple(std::string_view lexical_form, NodeStorage &node_storage = NodeStorage::default_instance());
 
+    /**
+     * Constructs a simple Literal from a lexical form. Datatype is `xsd:string`.
+     * normalizes lexical_form to UTF-8 NFC.
+     * @param lexical_form the lexical form
+     * @param node_storage optional custom node_storage used to store the literal
+     */
+    [[nodiscard]] static Literal make_simple_normalize(std::string_view lexical_form, NodeStorage &node_storage = NodeStorage::default_instance());
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.hpp:178]: What happens if you provide invalid Unicode here? Is it an exception or are the invalid chars replaced by the unicode invalid character char-thing?

File: src/rdf4cpp/rdf/Literal.cpp [hunk 16]
```diff
@@ -101,36 +101,52 @@ Literal Literal::make_string_like_copy_lang_tag(std::string_view str, Literal co
     return Literal::make_simple_unchecked(str, node_storage);
 }
 
-bool Literal::dynamic_datatype_eq_impl(std::string_view datatype) const noexcept {
-    assert(!this->is_fixed());
-    return this->datatype().identifier() == datatype;
-}
+    bool Literal::dynamic_datatype_eq_impl(std::string_view datatype) const noexcept {
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: Formatting still broken

File: src/rdf4cpp/rdf/Literal.cpp [hunk 17]
```diff
@@ -1658,6 +1690,10 @@ Literal Literal::sha512(NodeStorage &node_storage) const {
     return this->hash_with("SHA2-512", node_storage);
 }
 
+    std::string normalize_unicode(std::string_view utf8) {
```
Comment (liss-h) [inline src/rdf4cpp/rdf/Literal.cpp]: another formatting bug

**Review by liss-h — CHANGES_REQUESTED** [review]
Formatting still borked 😅

File: src/rdf4cpp/rdf/Literal.hpp (hunk 15 above)
Comment (mcb5637) [reply src/rdf4cpp/rdf/Literal.hpp:178]: replaced by replacement character codepoints (thats what the unicode standard says should happen) (and yes, there are more of them, but they basically all have the same purpose)

Comment (liss-h) [reply src/rdf4cpp/rdf/Literal.hpp:178]: makes sense, thx for clarifying

**Review by liss-h — APPROVED** [review]
